# Generated by Django 3.1.3 on 2021-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210126_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=7)),
                ('genre', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
