# Generated by Django 3.1.3 on 2021-01-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookhouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhouse',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
